name: Stubborn Old Gardeners
favicon: null
layout_spectrum: 0.4610369894653559
typography_spectrum: 0.8951958401594311
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f7fbe0'
    - '#8a9f74'
    - '#182615'
    - '#4e6811'
    - '#9b7c68'
  brandStrength: 0.5
  lightness: 0.8239924558438361
  saturation: 0.41986650973558426
  rhythmicContrast: 0.9118881651666015
purpose: []
